### ISSUE TITLE
New blog is not picked up by planet-gluster

### ISSUE THREAD

**Issue by karthik-us** [gluster/planet-gluster#58]
I have published a new blog on blogger/blogspot last week and added the "gluster" tag to that. But the blog is still not being picked up by planet-gluster. I already have my blogs feed link in the feeds.yaml file (feed: http://uskarthik.blogspot.com/feeds/posts/default/-/gluster) where I am able to see my latest blog named "Entries are not getting healed!!!". Can anyone check what is the problem and fix this?

**Comment by karthik-us** [comment]
Blog URL: https://uskarthik.blogspot.com/2020/02/entries-are-not-getting-healed-what-is_26.html

**Comment by mscherer** [comment]
So, the build is broken because newer nokogiri requires ruby 2.3.0 , and we are building on EL7. That is going to take some time.

**Comment by mscherer** [comment]
@amarts , seems the update of nokogiri (00fd10618ffc33f060d63a5d4f9b8f8741e61e29) broke the build, since newer nokogiri requires a newer version of Ruby (2.3.0).

**Comment by mscherer** [comment]
I am going to reinstall the builder on F31 to fix that.

**Comment by mscherer** [comment]
So, there is a issue with the automated installation, still on it.

**Comment by mscherer** [comment]
And F31 can't be automatically installed, so that will be F30 + upgrade, so please wait.

**Comment by mscherer** [comment]
So, now, planet do not build at all. I am debugging it.

**Comment by mscherer** [comment]
Still not building. A haml issue, the generate template has a syntax error. I am going to push the jenkins job so folks can see the issue, but I doubt I will fix before end of the week

**Comment by mscherer** [comment]
https://review.gluster.org/#/c/build-jobs/+/24216/ for the move to jenkins

**Comment by karthik-us** [comment]
@mscherer Any luck on this?

**Comment by mscherer** [comment]
So, I fixed that late night, after finding  1 change in haml that was blocking, 1 error triggered by a specific entry (still unsure why there was no title), 1 change in Feedjira that was hidden by one bug in the code base (never catch exception without displaying them, and never catch all of them when you just want 1), and while on it, also fixed a few feeds. 

I also merged my own patch (while we should have review), and I am trying to set CI on github, but right now, I am deep into some weird jenkins bug.

**Comment by karthik-us** [comment]
Hi @mscherer now I can see the latest blogs on planet.glutser including mine. Thanks for fixing this. If the jenkins bug you mentioned is not related to this or can be tracked as a new issue, then we can close this I guess.

**Comment by harigowtham** [comment]
@mscherer for some reason I see blogs only till 4 months ago. Is this a restriction that has been put? Because I posted a blog a long time ago and I too never saw it on planet gluster. And it still remains in the same state. both https://medium.com/@harigowtham/glusterfs-quotas-accounting-6ee60c78bb1f and https://medium.com/@harigowtham/glusterfs-quota-fix-accounting-840df33fcd3a Can you please check?
